on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 2 * *"

name: check

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3

      - name: Install SFML
        run: sudo apt install libsfml-dev

      - name: Install Codecov
        run: sudo pip install codecov

      - name: Allow measuring codecov
        run: sed -i 's/# LIBS += -lgcov/LIBS += -lgcov/' game.pro

      - name: qmake
        run: qmake game.pro

      - name: make
        run: make debug --silent

      - name: run
        run: ./game

      - name: Measure codecov 1
        run: ./get_code_cov.sh

      - name: Measure codecov 2
        run: codecov

      - name: Measure codecov 3
        run: bash <(curl -s https://codecov.io/bash)

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: clean for release build
        run: make clean

      - name: qmake
        run: qmake game.pro

      - name: make
        run: make release --silent

      - name: Show contributors on all branches
        run: git clone https://github.com/tresinformal/basketball.git ; cd basketball ; git shortlog -s -n --all --no-merges

